/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [DateKey]
      ,[FullDate]
      ,[DateName]
      ,[DayOfWeek]
      ,[DayNameOfWeek]
      ,[DayOfMonth]
      ,[DayOfYear]
      ,[WeekdayWeekend]
      ,[WeekOfYear]
      ,[MonthName]
      ,[MonthOfYear]
      ,[IsLastDayOfMonth]
      ,[CalendarQuarter]
      ,[CalendarYear]
      ,[CalendarYearMonth]
      ,[CalendarYearQtr]
      ,[FiscalMonthOfYear]
      ,[FiscalQuarter]
      ,[FiscalYear]
      ,[FiscalYearMonth]
      ,[FiscalYearQtr]
  FROM [DWCompetitionTaskNSW].[dbo].[DimDate]