/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [SchoolKey]
      ,[SchoolId]
      ,[Postcode]
      ,[School_Name]
      ,[School_Address]
      ,[Town_Suburb]
      ,[School_Latitude]
      ,[School_Longitude]
      ,[Student_Number]
      ,[ICSEA_Value]
      ,[Level_of_Schooling]
      ,[School_Specialty_type]
      ,[School_Subtype]
      ,[School_Gender]
      ,[State_Code]
  FROM [DWCompetitionTaskNSW].[dbo].[Dim_SchoolTable]